services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password

  neo4j_test:
    image: neo4j:latest
    container_name: neo4j_test
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      
  app:
    build: .
    container_name: covid19-api
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
      - neo4j_test
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_TEST_URI: bolt://neo4j_test:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      LOAD_DATA: "true"  # Variável de ambiente para controlar o carregamento de dados
